name: Set up java runtime

runs:
  using: composite
  steps:
    # https://github.com/actions/setup-java
    - uses: actions/setup-java@v4
      with:
        java-version-file: '.java-version'
        distribution: 'microsoft'
