@startuml

circle "WebAPI Module" as WebAPI

entity RepositoryEntity {
    +forkCount: Int
    +issueCount: Int
    +language: String?
    +name: String
    +ownerIconUrl: URL?
    +ownerName: String
    +starCount: Int
    +watcherCount: Int

    +{static} parseOrNull(...): ...?
}
note right of RepositoryEntity::forkCount
    0以上
end note
note right of RepositoryEntity::issueCount
    0以上
end note
note right of RepositoryEntity::ownerIconUrl
    URI 形式
end note
note right of RepositoryEntity::starCount
    0以上
end note
note right of RepositoryEntity::watcherCount
    0以上
end note
note bottom of RepositoryEntity : リポジトリ情報

entity RepositoryQueryEntity {
    +keyword: String
    +page: Int
    .. 既定値 ..
    +order: String = "desc"
    +perPage: Int = 50
    +sort: String? = null

    +{static} newInstance(keyword: String?, page: Int): ...
}
note left of RepositoryQueryEntity::keyword
    1文字以上
end note
note left of RepositoryQueryEntity::page
    0以上
end note
note top of RepositoryQueryEntity : リポジトリの検索条件

entity RepositoryResultEntity {
    + hasMore: Boolean
    + items: List<RepositoryEntity>
}
note top of RepositoryResultEntity : リポジトリの検索結果

interface GitHubRepositoryContract {
    +search(query: RepositoryQueryEntity): RepositoryResultEntity
}
note top of GitHubRepositoryContract : GitHub に関するデータのリポジトリ定義


RepositoryQueryEntity .right.> GitHubRepositoryContract
GitHubRepositoryContract <.down.> WebAPI
GitHubRepositoryContract .right.> RepositoryResultEntity
RepositoryResultEntity o-down- RepositoryEntity

@enduml