@startuml
actor User
box "App" #LightBlue
    participant 結果一覧画面 as IndexPage
    participant 詳細画面 as DetailPage
end box
participant "GitHub REST API" as GitHub


== アプリ起動フロー ==
User -> IndexPage : (アプリ起動)
activate IndexPage
return 結果一覧画面の表示


== 検索フロー ==
User -> IndexPage : 検索ワードの入力 & 検索実行
activate IndexPage
IndexPage -> GitHub : HTTPS 通信の実行
activate GitHub
note right of GitHub
    GET /search/repositories
end note
return 通信結果
return 検索結果の表示

...

User -> IndexPage : 検索結果の中から任意のものをタップ
IndexPage -> DetailPage : 検索結果を添えて画面遷移
DetailPage --> User : 詳細画面の表示

@enduml