name: 140 Create version pull request

on:
  workflow_dispatch:
    inputs:
      versionMajor:
        description: 'バージョン情報: major'
        required: true
        type: string
      versionMinor:
        description: 'バージョン情報: minor'
        required: true
        type: string
      versionPatch:
        description: 'バージョン情報: patch'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  create-version-pr:
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-java-runtime

      - name: Update version
        id: version
        run: |
          jshell -R-Dargs="${{ inputs.versionMajor }} ${{ inputs.versionMinor }} ${{ inputs.versionPatch }}" .github/scripts/set-version/set-version.jsh
          echo "$(jshell .github/scripts/get-version-name/get-version-name.jsh)" > TMP_LOG
          if gh release view $(cat TMP_LOG) > /dev/null; then
            echo "$(cat TMP_LOG) is already released!"
            exit 1
          fi
          echo "branch-name=feature/update_$(cat TMP_LOG)" >> "$GITHUB_OUTPUT"
          echo "message=アプリバージョン更新: $(cat TMP_LOG)" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: ./.github/actions/apply-gh-actions-bot-identity

      - name: Git push
        run: |
          git switch --create ${{ steps.version.outputs.branch-name }}
          git add --all
          git commit --message "${{ steps.version.outputs.message }}"
          git push --set-upstream origin ${{ steps.version.outputs.branch-name }}

      - name: Create pull request
        run: |
          gh pr create --base ${{ github.ref_name }} --title "${{ steps.version.outputs.message }}" --body "## 確認事項
          * [ ] 意図したバージョンが設定されている
          * [ ] ビルド出来る"
        env:
          GITHUB_TOKEN: ${{ github.token }}
