name: 160 Create release pull request

on:
  pull_request:
    types:
      - closed
    branches:
      - 'develop'
    paths:
      - 'build.properties'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  create-release-pr:
    if: >-
      github.ref_type == 'branch' &&
      (github.event_name == 'workflow_dispatch' ||
        (github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'アプリバージョン更新')))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-java-runtime

      - name: Get version name
        id: version
        run: |
          echo "$(jshell .github/scripts/get-version-name/get-version-name.jsh)" > TMP_LOG
          bash .github/scripts/can-release.bash $(cat TMP_LOG)
          echo "name=$(cat TMP_LOG)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Generate diff notes
        id: notes
        run: echo "response=$(bash .github/scripts/presume-release-notes.bash preview${{ steps.version.outputs.name }} ${{ github.ref_name }})" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Create pull request
        run: gh pr create --base released --title "Merge ${{ steps.version.outputs.name }}" --body "${{ fromJson(steps.notes.outputs.response).body }}"
        env:
          GH_TOKEN: ${{ github.token }}
