name: reviewdog

on:
  pull_request:
    branches: [ "develop" ]
  
jobs:
  reviewdog:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/timheuer/base64-to-file
      - name: Set google-services.json
        id: set_google_services
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'google-services.json'
          fileDir: './app/'
          encodedString: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Set keystore's file
        id: set_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'release.jks'
          fileDir: './'
          encodedString: ${{ secrets.KEYSTORE }}

      - uses: ./.github/actions/setup-java-runtime

      # https://github.com/gradle/actions
      - uses: gradle/actions/setup-gradle@v4

      - run: chmod +x gradlew

      - name: Build manually
        run: ./gradlew app:assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      
      # https://github.com/reviewdog/reviewdog
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      # https://github.com/reviewdog/action-actionlint
      - uses: reviewdog/action-actionlint@v1

      # https://github.com/DVDAndroid/action-android-lint
      - uses: dvdandroid/action-android-lint@master

      # https://github.com/ScaCap/action-ktlint
      - uses: ScaCap/action-ktlint@master
