name: reviewdog
on: pull_request
  
jobs:
  reviewdog:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-java-runtime

      # https://github.com/gradle/actions
      - uses: gradle/actions/setup-gradle@v4

      - run: chmod +x gradlew

      - run: ./gradlew build
      
      # https://github.com/reviewdog/reviewdog
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      # https://github.com/reviewdog/action-actionlint
      - uses: reviewdog/action-actionlint@v1

      # https://github.com/DVDAndroid/action-android-lint
      - uses: dvdandroid/action-android-lint@master

      # https://github.com/ScaCap/action-ktlint
      - uses: ScaCap/action-ktlint@master
